# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language

#languages:
  #pt:
   # languageName: Portuguese
    #weight: 1
    #contentDir: content/pt

  #en:
   # languageName: English
    #weight: 2
    #contentDir: content/en'


en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#pt:
#  languageCode: pt-br
#  contentDir: content/pt
#  title: Portuguese website title...
#  params:
#    description: Site description in Portuguese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
